name: yaru_window_example
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  handy_window: ^0.2.0
  yaru: ^0.5.0
  yaru_widgets: # ^2.0.0
    git:
      url: https://github.com/jpnurmi/yaru_widgets.dart
      ref: title-bar-2
  yaru_window:
    path: ../

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
