name: yaru_window
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.8.0
  plugin_platform_interface: ^2.0.2
  yaru_widgets: # ^2.0.0
    git:
      url: https://github.com/jpnurmi/yaru_widgets.dart
      ref: title-bar-2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: YaruWindowPlugin
      macos:
        pluginClass: YaruWindowPlugin
      windows:
        pluginClass: YaruWindowPluginCApi
